[package]
name = "suplock"
version = "0.1.0"

[dependencies]
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "main", subdir = "aptos-move/framework/aptos-stdlib" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "main", subdir = "aptos-move/framework/move-stdlib" }

[addresses]
suplock = "0x0"
std = "0x1"
supra = "0x2"
