import React from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  X,
  BookOpen,
  Lock,
  Vote,
  Zap,
  Database,
  Shield,
  TrendingDown,
  Coins,
  Layers,
  ExternalLink,
} from "lucide-react";

interface LearnDrawerProps {
  isOpen: boolean;
  onClose: () => void;
}

const concepts = [
  {
    id: "autofi",
    icon: Zap,
    title: "AutoFi: Self-Executing DeFi",
    description:
      "AutoFi represents the next evolution of decentralized finance where protocols operate autonomously without manual intervention.",
    details: [
      "Automated yield optimization across multiple strategies",
      "Self-executing buyback and burn mechanisms",
      "24/7 fee distribution without admin action",
      "Intent-based execution that protects users from MEV",
    ],
    highlight:
      "Traditional DeFi requires constant manual management. AutoFi protocols like SUPLOCK handle everything automatically, ensuring you never miss an opportunity.",
  },
  {
    id: "vesupra",
    icon: Lock,
    title: "Vote-Escrow Locking (veSUPRA)",
    description:
      "Lock your $SUPRA tokens to receive veSUPRA NFTs that grant governance power and yield boosts up to 2.5x.",
    details: [
      "Lock duration: 3 months to 4 years (48 months)",
      "Boost formula: 1 + (months/48) × 1.5",
      "NFTs are soulbound for 30 days, then transferable",
      "Longer locks = more governance voting power",
    ],
    highlight:
      "Why lock? You earn protocol revenue shares, get priority vault access, and your voice shapes the protocol's future through DAO voting.",
  },
  {
    id: "floor",
    icon: TrendingDown,
    title: "The 10 Billion Floor Mechanism",
    description:
      "SUPLOCK's core mission: reduce $SUPRA supply from ~45B to a permanent floor of 10B tokens through systematic buybacks and burns.",
    details: [
      "Current supply: ~45 billion $SUPRA tokens",
      "Target floor: 10 billion tokens",
      "Pre-floor: 50% of fees fund buyback & burn",
      "Post-floor: Burns stop, 65% goes to dividends",
    ],
    highlight:
      "This creates predictable, sustained deflation. Once the floor is reached, all burn allocation converts to holder dividends, maximizing long-term returns.",
  },
  {
    id: "supreserve",
    icon: Database,
    title: "SUPReserve: The Flywheel Engine",
    description:
      "SUPReserve aggregates all protocol fees and distributes them automatically based on supply levels.",
    details: [
      "Collects USDC from all protocol activities",
      "Monthly automated distribution",
      "Pre-floor: 50% burn, 35% dividends, 10% veSUPRA, 5% treasury",
      "Post-floor: 0% burn, 65% dividends, 12.5% veSUPRA, 12.5% treasury",
    ],
    highlight:
      "Think of SUPReserve as a self-sustaining engine that rewards holders while systematically increasing token scarcity.",
  },
  {
    id: "vaults",
    icon: Layers,
    title: "Yield Vaults & PT/YT Splitting",
    description:
      "Deposit into optimized yield vaults that split your position into tradeable Principal (PT) and Yield (YT) tokens.",
    details: [
      "PT = Principal Token (your original deposit)",
      "YT = Yield Token (your future earnings)",
      "Both tokens are separately tradeable",
      "EigenLayer & Symbiotic restaking integration",
    ],
    highlight:
      "Advanced strategy: Keep your YT for long-term yield while selling PT for instant liquidity—or vice versa. Maximum capital flexibility.",
  },
  {
    id: "privacy",
    icon: Shield,
    title: "LP Vacuum: MEV Protection",
    description:
      "LP Vacuum encrypts all trading intents, protecting you from front-running, sandwich attacks, and other MEV extraction.",
    details: [
      "Encrypted intents until execution",
      "No front-running possible",
      "No sandwich attacks",
      "Captured MEV redistributed to users",
    ],
    highlight:
      "On typical DEXs, bots steal value from your trades. LP Vacuum ensures you get fair execution and captures that value for the protocol instead.",
  },
  {
    id: "governance",
    icon: Vote,
    title: "Decentralized Governance",
    description:
      "veSUPRA holders control protocol parameters through transparent on-chain voting with timelock security.",
    details: [
      "One veSUPRA = one vote",
      "7-day voting period for proposals",
      "3-day execution timelock for security",
      "Vote on fees, allocations, new features",
    ],
    highlight:
      "True community ownership. No central team can change parameters without majority veSUPRA holder approval.",
  },
  {
    id: "dividends",
    icon: Coins,
    title: "Protocol Revenue Sharing",
    description:
      "veSUPRA holders receive real yield from protocol fees—not inflationary emissions, but actual revenue generated by the ecosystem.",
    details: [
      "35-65% of all fees go to dividends",
      "Paid in USDC (stablecoin)",
      "Claimable anytime from Reserve",
      "Proportional to your veSUPRA balance",
    ],
    highlight:
      "Real yield, not token printing. Your dividends come from actual protocol usage, creating sustainable, long-term value.",
  },
];

export function LearnDrawer({ isOpen, onClose }: LearnDrawerProps) {
  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/80 backdrop-blur-sm z-[200]"
          />

          {/* Drawer */}
          <motion.div
            initial={{ x: "100%" }}
            animate={{ x: 0 }}
            exit={{ x: "100%" }}
            transition={{ type: "spring", damping: 30, stiffness: 300 }}
            className="fixed right-0 top-0 h-full w-full max-w-xl bg-background border-l border-primary/30 z-[201] overflow-hidden flex flex-col"
          >
            {/* Header */}
            <div className="flex items-center justify-between p-6 border-b border-primary/20 bg-primary/5">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-primary/10 border border-primary/30">
                  <BookOpen className="w-5 h-5 text-primary" />
                </div>
                <div>
                  <h2 className="text-lg font-bold uppercase tracking-tight neon-text">
                    Learn SUPLOCK
                  </h2>
                  <p className="text-[10px] text-primary/60 uppercase tracking-widest">
                    Protocol Education Hub
                  </p>
                </div>
              </div>
              <button
                onClick={onClose}
                className="p-2 hover:bg-primary/10 border border-transparent hover:border-primary/30 transition-all"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-y-auto p-6 space-y-6">
              {/* Intro Banner */}
              <div className="p-4 bg-primary/5 border border-primary/20 space-y-2">
                <h3 className="text-xs font-bold uppercase tracking-widest text-primary">
                  What is SUPLOCK?
                </h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  SUPLOCK is an <strong className="text-primary">AutoFi protocol</strong> on Supra L1 that creates sustainable tokenomics for $SUPRA holders. We combine vote-escrow locking, automated burns, and yield optimization to build long-term value.
                </p>
                <p className="text-xs text-primary/60 italic">
                  Our motto: "Burn to Floor. Yield Forever."
                </p>
              </div>

              {/* Concepts */}
              <div className="space-y-4">
                {concepts.map((concept, index) => (
                  <motion.div
                    key={concept.id}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: index * 0.05 }}
                    className="matrix-card p-5 space-y-4"
                  >
                    <div className="flex items-start gap-3">
                      <div className="p-2 bg-primary/10 border border-primary/20">
                        <concept.icon className="w-5 h-5 text-primary" />
                      </div>
                      <div className="flex-1">
                        <h4 className="text-sm font-bold uppercase tracking-tight">
                          {concept.title}
                        </h4>
                        <p className="text-xs text-muted-foreground mt-1 leading-relaxed">
                          {concept.description}
                        </p>
                      </div>
                    </div>

                    <ul className="space-y-1 pl-4">
                      {concept.details.map((detail, i) => (
                        <li
                          key={i}
                          className="text-[11px] text-primary/70 flex items-start gap-2"
                        >
                          <span className="w-1 h-1 bg-primary rotate-45 mt-1.5 shrink-0" />
                          {detail}
                        </li>
                      ))}
                    </ul>

                    <div className="p-3 bg-accent/5 border-l-2 border-accent">
                      <p className="text-[11px] text-accent/90 leading-relaxed">
                        {concept.highlight}
                      </p>
                    </div>
                  </motion.div>
                ))}
              </div>

              {/* External Links */}
              <div className="p-4 bg-primary/5 border border-primary/20 space-y-3">
                <h4 className="text-xs font-bold uppercase tracking-widest text-primary">
                  Dive Deeper
                </h4>
                <div className="flex flex-wrap gap-2">
                  <a
                    href="https://gamma.app/docs/AutoFi-The-Future-of-Self-Executing-DeFi-netu8419zs14xx8"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center gap-1.5 text-[10px] px-3 py-1.5 bg-primary/10 border border-primary/30 hover:bg-primary/20 transition-colors uppercase font-bold"
                  >
                    <ExternalLink className="w-3 h-3" />
                    Phase 1 Whitepaper
                  </a>
                  <a
                    href="https://gamma.app/docs/The-Future-of-DeFi-is-Autonomous-t8cilvep4vid95g"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center gap-1.5 text-[10px] px-3 py-1.5 bg-primary/10 border border-primary/30 hover:bg-primary/20 transition-colors uppercase font-bold"
                  >
                    <ExternalLink className="w-3 h-3" />
                    Phase 2 Whitepaper
                  </a>
                </div>
              </div>
            </div>

            {/* Footer */}
            <div className="p-4 border-t border-primary/20 bg-primary/5">
              <p className="text-[10px] text-primary/40 text-center uppercase tracking-widest">
                Built for Supra L1 Community
              </p>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
